### ISSUE TITLE
Unexpected DB error when adding Permissions using new EOS GUID

### ISSUE THREAD

**Issue by ViperGeek** [ServersHub/ServerAPI-Plugins#4]
Permissions.AddTribe seems to work fine in ASA, although I can't seem to add Default (it says "Tribe was already added" despite it not showing up in the tribepermissions table in MySQL). My problem comes when trying to Permissions.Add by EOS ID. For example:
```
> Permissions.AddGroup PermTest
(SERVER): Successfully added group
> Permissions.Add 0002d4e850b94802b18a99e49dee5040 PermTest
(SERVER): Unexpected DB error
```
The ArkApi log shows:

`11/25/23 03:35 [Permission][error] (E:\_dev\ark_api\_ASA\API\ServerAPI-Plugins\Permissions\Permissions\Private\Hooks.cpp Permissions::Hooks::Hook_AShooterGameMode_HandleNewPlayer) Couldn't add player`

I'm using the same schemas and tables from my ASE Permissions plug-in installation, in case that's a problem.

**Comment by Pelayori** [comment]
@ViperGeek what's your schema like?
If you are using the ASE schema, you would need to update `SteamId` column to be `EOS_Id`, and change type from `BIGINT UNSIGNED` to `VARCHAR`

SteamIDs cannot be converted to EOS_Ids at the moment, so the data is not interchangeable.

**Comment by Lethalinjectionx** [comment]
In simple terms you cannot use the ASE database tables for ASA.

**Comment by ViperGeek** [comment]
Thanks @Pelayori and @Lethalinjectionx.  I'll change my config.json to:

`"MysqlDB":"ark_permissions_asa"`

once my last straggler user disconnects from the server.

**Comment by Pelayori** [comment]
> Thanks @Pelayori and @Lethalinjectionx. I'll change my config.json to:
> 
> `"MysqlDB":"ark_permissions_asa"`
> 
> once my last straggler user disconnects from the server.

As long as arkshop can create its own table it should be fine.

**Comment by SubstituteR** [comment]
This sounds like an area where we can add documentation explaining the difference between the ase shop with Steam64 ids and the asa shop with EOS GUIDs.

**Comment by ViperGeek** [comment]
New errors:

```
11/28/23 11:25 [Permission][critical] Failed to open connection!
11/28/23 11:25 [API][warning] (API::PluginManager::LoadAllPlugins) Failed to load plugin - Permissions
Error code: 1114
```

Can you remind me if I have to manually create the new schema?

**Comment by Lethalinjectionx** [comment]
You need the database in place the plugin will create the tables for you.

**Comment by ViperGeek** [comment]
Worked perfectly:
```
Permissions.AddGroup PermTest (PlayerName: ViperGeek, ARKID: 782174920, SteamID: 0002d4e850b94802b18a99e49dee5040)
Permissions.Add 0002d4e850b94802b18a99e49dee5040 PermTest (PlayerName: ViperGeek, ARKID: 782174920, SteamID: 0002d4e850b94802b18a99e49dee5040)
```

Thanks all.  This issue can be closed as Resolved.
